# Generated by Django 5.0.4 on 2024-05-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0002_complaint_alter_contato_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='data',
        ),
        migrations.AddField(
            model_name='complaint',
            name='nome',
            field=models.CharField(default=111, max_length=30),
            preserve_default=False,
        ),
    ]
