# Generated by Django 5.0.4 on 2024-05-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0003_remove_complaint_data_complaint_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='email',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='nome',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='assunto',
            field=models.TextField(),
        ),
    ]
