# Generated by Django 5.0.4 on 2024-04-22 20:36

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_product_is_sale_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name=django.contrib.auth.models.User)),
                ('Numero', models.CharField(blank=True, max_length=20)),
                ('Endereço1', models.CharField(blank=True, max_length=200)),
                ('Endereço2', models.CharField(blank=True, max_length=200)),
                ('Cidade', models.CharField(blank=True, max_length=200)),
                ('Estado', models.CharField(blank=True, max_length=200)),
                ('CEP', models.CharField(blank=True, max_length=200)),
                ('País', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
