# Generated by Django 5.0.4 on 2024-04-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='antigo_carrinho',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
