# Generated by Django 5.0.3 on 2024-04-26 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
