# Generated by Django 5.0.6 on 2024-05-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_delete_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='antigo_favoritos',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
