# Generated by Django 5.0.6 on 2024-05-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_profile_antigo_favoritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='CEP',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Numero',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
