# Generated by Django 5.0.6 on 2024-05-15 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_profile_cep_alter_profile_numero_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Endereço1',
            new_name='Endereco1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Endereço2',
            new_name='Endereco2',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='País',
            new_name='Pais',
        ),
    ]
