# Generated by Django 5.0.4 on 2024-05-16 18:34

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_endereço1_profile_endereco1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Endereco1',
            new_name='Endereço1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Endereco2',
            new_name='Endereço2',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Pais',
            new_name='País',
        ),
        migrations.AlterField(
            model_name='profile',
            name='CEP',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
