from django.test import LiveServerTestCase
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.select import Select
from selenium import webdriver
import time

driver = webdriver.Chrome()

class AtualizarPerfil(LiveServerTestCase):

    def test_cenario1(self):
        driver.get("http://127.0.0.1:8000/register/")
        usuario = driver.find_element(by=By.NAME, value="username")
        nome = driver.find_element(by=By.NAME, value="first_name")
        sobrenome = driver.find_element(by=By.NAME, value="last_name")
        email = driver.find_element(by=By.NAME, value="email")
        senha = driver.find_element(by=By.NAME, value="password1")
        confirmar_senha = driver.find_element(by=By.NAME, value="password2")
        botao = driver.find_element(by=By.NAME, value="registro")

        usuario.send_keys(f"User_1")
        nome.send_keys(f"jerivaldo")
        sobrenome.send_keys(f"mamanguape")
        email.send_keys(f"jerivaldomamanguape@gmail.com")
        senha.send_keys("Senha1234")
        confirmar_senha.send_keys("Senha1234")
        botao.send_keys(Keys.ENTER)

        driver.get("http://127.0.0.1:8000/update_info/")
        numero = driver.find_element(by=By.NAME, value="Numero")
        endereco1 = driver.find_element(by=By.NAME, value="Endereço1")
        endereco2 = driver.find_element(by=By.NAME, value="Endereço2")
        cidade = driver.find_element(by=By.NAME, value="Cidade")
        estado = driver.find_element(by=By.NAME, value="Estado")
        cep = driver.find_element(by=By.NAME, value="CEP")
        pais = driver.find_element(by=By.NAME, value="País")
        botao2 = driver.find_element(by=By.NAME, value="atualizar")

        numero.send_keys("8199999999")
        endereco1.send_keys(f"Ibura, 420")
        endereco2.send_keys(f"Rua Cais do Apolo, 77")
        cidade.send_keys(f"Recife")
        estado.send_keys(f"Pernambuco")
        cep.send_keys("123456789")
        pais.send_keys(f"Brasil")
        botao2.send_keys(Keys.ENTER)
        time.sleep(3)
        self.assertEqual(driver.find_element(by=By.NAME, value="title").text,"iTech Store")
        driver.get("http://127.0.0.1:8000/logout/")
        time.sleep(4)

    def test_cenario2(self):
        driver.get("http://127.0.0.1:8000/register/")
        usuario = driver.find_element(by=By.NAME, value="username")
        nome = driver.find_element(by=By.NAME, value="first_name")
        sobrenome = driver.find_element(by=By.NAME, value="last_name")
        email = driver.find_element(by=By.NAME, value="email")
        senha = driver.find_element(by=By.NAME, value="password1")
        confirmar_senha = driver.find_element(by=By.NAME, value="password2")
        botao = driver.find_element(by=By.NAME, value="registro")

        usuario.send_keys(f"User_2")
        nome.send_keys(f"ricardo")
        sobrenome.send_keys(f"cesar")
        email.send_keys(f"ricardocesar@gmail.com")
        senha.send_keys("Senha1234")
        confirmar_senha.send_keys("Senha1234")
        botao.send_keys(Keys.ENTER)

        driver.get("http://127.0.0.1:8000/update_info/")
        numero = driver.find_element(by=By.NAME, value="Numero")
        endereco1 = driver.find_element(by=By.NAME, value="Endereço1")
        endereco2 = driver.find_element(by=By.NAME, value="Endereço2")
        cidade = driver.find_element(by=By.NAME, value="Cidade")
        estado = driver.find_element(by=By.NAME, value="Estado")
        cep = driver.find_element(by=By.NAME, value="CEP")
        pais = driver.find_element(by=By.NAME, value="País")
        botao2 = driver.find_element(by=By.NAME, value="atualizar")

        numero.send_keys("8199999990")
        endereco1.send_keys(f"IPSEP, 69")
        endereco2.send_keys(f"Rua Cais do Apolo, 77")
        cidade.send_keys(f"Recife")
        estado.send_keys(f"Pernambuco")
        cep.send_keys("123456789")
        pais.send_keys(f"Brasil")
        botao2.send_keys(Keys.ENTER)
        time.sleep(1)

        driver.get("http://127.0.0.1:8000/logout/")

        driver.get("http://127.0.0.1:8000/register/")
        usuario = driver.find_element(by=By.NAME, value="username")
        nome = driver.find_element(by=By.NAME, value="first_name")
        sobrenome = driver.find_element(by=By.NAME, value="last_name")
        email = driver.find_element(by=By.NAME, value="email")
        senha = driver.find_element(by=By.NAME, value="password1")
        confirmar_senha = driver.find_element(by=By.NAME, value="password2")
        botao = driver.find_element(by=By.NAME, value="registro")

        usuario.send_keys(f"User_3")
        nome.send_keys(f"andre")
        sobrenome.send_keys(f"castro")
        email.send_keys(f"ginho@gmail.com")
        senha.send_keys("Senha1234")
        confirmar_senha.send_keys("Senha1234")
        botao.send_keys(Keys.ENTER)

        driver.get("http://127.0.0.1:8000/update_info/")
        numero = driver.find_element(by=By.NAME, value="Numero")
        endereco1 = driver.find_element(by=By.NAME, value="Endereço1")
        endereco2 = driver.find_element(by=By.NAME, value="Endereço2")
        cidade = driver.find_element(by=By.NAME, value="Cidade")
        estado = driver.find_element(by=By.NAME, value="Estado")
        cep = driver.find_element(by=By.NAME, value="CEP")
        pais = driver.find_element(by=By.NAME, value="País")
        botao2 = driver.find_element(by=By.NAME, value="atualizar")

        numero.send_keys("8199999992")
        endereco1.send_keys(f"Olinda, 98")
        endereco2.send_keys(f"Rua Cais do Apolo, 77")
        cidade.send_keys(f"Recife")
        estado.send_keys(f"Pernambuco")
        cep.send_keys("123456789")
        pais.send_keys(f"Brasil")
        botao2.send_keys(Keys.ENTER)
        time.sleep(3)
        self.assertEqual(driver.find_element(by=By.NAME, value="title").text,"iTech Store")
        driver.get("http://127.0.0.1:8000/logout/")
        time.sleep(4)