# Generated by Django 5.0.4 on 2024-06-26 20:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='date',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
