name: CI - iTechDeployment

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          set -ex
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        with:
          version: latest

      - name: Run local server and tests
        run: |
          python manage.py makemigrations
          python manage.py migrate
          python manage.py runserver &
          sleep 5
          python manage.py test store.tests

      
